### ISSUE TITLE
navigationOptions not working with react-navigation

### ISSUE THREAD

**Issue by levipro** [expo/react-native-action-sheet#125]
I recently upgraded one of my projects and noticed on the screen where I used connectActionSheet that my navigationOptions for react-navigation were no longer working (title and buttons were not showing).

I'm just wondering what the reason for removing hoist-non-react-statics was. Does it not work with the new react context api?

Now I'm setting navigationOptions after I apply connectActionSheet to my component and it is working fine.

If the old behaviour of automatically hoisting the statics to the connected component can't be added back then maybe this should be documented.

**Comment by gavrichards** [comment]
@levipro Where is `connect()` coming from in your example, and what are `mapStateToProps` and `actions`?
And how would the action sheet then be called?

**Comment by mitesh-mokko** [comment]
I believe `connect()` is from `react-redux` and is just redux boilerplate (including `mapStateToProps` and `actions`). You can ignore those. The main helpful thing here to note is that the navigationOptions are declared on the `ConnectedApp` rather than in `Screen` which used to be the case in my code too.

**Comment by rikardwissing** [comment]
We have this issue as well. I have created a PR hoisting statics of components with connected action sheet.

**Comment by jdhorner** [comment]
Can't wait for the PR fixing this to be merged and released! (Hopefully soon?)
