### ISSUE TITLE
How to change option's height

### ISSUE THREAD

**Issue by EricaLi123** [expo/react-native-action-sheet#250]

**Comment by MartinGao** [comment]
Hi, I know this issue has been closed but I also have this issue and could not find the solution
I would like to display a couple of options when the device is in landscape mode. 
I want to set the height of options to be as small as possible so that I could fit more options without scrolling
I am able to adjust the text size using `textStyle` but  I can't change the height of one option.
I tried `containerStyle` but it just change the height of the whole action sheet which is not what I want.
