### ISSUE TITLE
module no longer referenced in npm

### ISSUE THREAD

**Issue by arsanjea** [expo/react-native-action-sheet#36]
Already opened same issue for fade-in:
For the past few hours, I've been having problems yarning my project:
Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "eslint-config-rallycoding"
npm ERR! node v6.9.4
npm ERR! npm v3.10.10

npm ERR! Invalid name: "@exponent/react-native-action-sheet"

same problem with react-native-fade-in-image

**Comment by brentvatne** [comment]
The name is now @expo/react-native-action-sheet although the previous one should still work ...

**Comment by nickkapoor** [comment]
I am getting an error when I run npm install @expo/react-native-action-sheet.  Could you please assist since this is being used by other components like gifted-chat.

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@expo/react-native-action-sheet"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@expo/react-native-action-sheet"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXX/development/AwesomeProject/npm-debug.log

**Comment by brentvatne** [comment]
Something is wrong with your machine as this works as expected for me and others. Perhaps you're not using the default npm registry. Sorry, debugging npm is outside of the scope of this repo!
